In [70]:
# Import pandas
import pandas as pd

In [71]:
# Create a DataFrame with balance.txt

df = pd.read_csv('balance.txt', delim_whitespace=True)

In [41]:
df.iloc[5:10]

,Balance,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity
5,22.486178,80.180,8047,569,4,77,10,Male,No,No,Caucasian
6,10.574516,20.996,3388,259,2,37,12,Female,No,No,African American
7,14.576204,71.408,7114,512,2,87,9,Male,No,No,Asian
8,7.938090,15.125,3300,266,5,66,13,Female,No,No,Caucasian
9,17.756965,71.061,6819,491,3,41,19,Female,Yes,Yes,African American

In [45]:
# Compare the average income based on ethnicity.
print("The average income for Caucasian is", df[df.Ethnicity == "Caucasian"].loc[:,"Income"].mean())
print("The average income for African American is", df[df.Ethnicity == "African American"].loc[:,"Income"].mean())
print("The average income for  Asian is", df[df.Ethnicity == "Asian"].loc[:,"Income"].mean())

The average income for Caucasian is 44.521944723618084
The average income for African American is 47.68210101010099
The average income for  Asian is 44.18783333333334

In [61]:
# On average, do married or single people have a higher balance? Single people

print(df.groupby('Married')['Balance'].mean(numeric_only=True))

Married
No     13.493509
Yes    13.388473
Name: Balance, dtype: float64

In [75]:
# What is the highest income in our dataset?
highest_income = df['Income'].max()
print("max income is:", highest_income)

max income is: 186.634

In [63]:
# What is the lowest income in our dataset?

min_income = df['Income'].min()

print("max income is:", min_income)

max income is: 10.354

In [64]:
# How many cards do we have recorded in our dataset? (Hint: use `sum()`)

df['Cards'].sum()

1183

In [81]:
# How many females do we have information for vs how many males? (Hint: use `count()

df['Gender'].value_counts()

Gender
Female    207
Male      193
Name: count, dtype: int64

In [90]:
df.columns

Index(['Balance', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Gender', 'Student', 'Married', 'Ethnicity'],
      dtype='object')

Write the code needed to produce a report that provides the following information:
* Compare the average income based on ethnicity.
* On average, do married or single people have a higher balance?
* What is the highest income in our dataset?
* What is the lowest income in our dataset?
* How many cards do we have recorded in our dataset? (Hint: use `sum()`)
* How many females do we have information for vs how many males? (Hint: use `count()` for a list of all methods for computation of descriptive stats, explore the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).